ARG UBUNTU_VERSION=jammy
FROM ubuntu:${UBUNTU_VERSION}

ENV HOMEDIR=/root

MAINTAINER Dongsheng Cai <d@tux.im>
WORKDIR $HOMEDIR

RUN pwd

RUN ["apt-get", "-y", "update"]
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    apt-transport-https \
    apt-utils \
    ca-certificates \
    curl \
    locales \
    software-properties-common

# configure locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8
RUN ln -fs /usr/share/zoneinfo/Australia/Sydney /etc/localtime

RUN add-apt-repository -y -n ppa:neovim-ppa/unstable
RUN add-apt-repository -y -n ppa:fish-shell/release-3
RUN add-apt-repository -y -n ppa:git-core/ppa
RUN ["apt-get", "-y", "update"]

# python layer
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3-pip \
    python3-pygments \
    python3-venv \
    virtualenv

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    aptitude \
    aria2 \
    aspell \
    cmake \
    fish \
    fzf \
    git \
    htop \
    jq \
    mcrypt \
    ncdu \
    neovim \
    ntp \
    ntpdate \
    p7zip \
    ripgrep \
    tig \
    tmux \
    tree \
    unrar \
    unzip \
    wajig \
    wbritish

ENTRYPOINT ["/usr/bin/fish"]
